// layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { EPDSProvider } from "./_context/EPDSResult";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata (title, description, etc.)
export const metadata: Metadata = {
  title: "EZCounselling EPDS",
  description: "Generated by create next app",
};

// Viewport (must be separate)
export const viewport = {
  width: "device-width",
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div>
          <main className="w-full max-w-[1000px] m-auto shadow-2xl shadow-black/30 bg-white ">
            <EPDSProvider>
              <Navbar />
              {children}
            </EPDSProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
